config/routes.rb
Rails.application.routes.draw do
  root 'main#index'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  devise_scope :user do
    get 'sign_in', :to => 'devise/sessions#new', :as => :sign_in
    get 'sign_out', :to => 'devise/sessions#destroy', :as => :sign_out
  end

  get 'user' => "user#index"
  resources :donations, only: [:create] do
    collection do
      get :user_ranking
    end
  end

  resources :disasters, only: [:index] do
    member do
      get :ranking
    end
  end

end

app/models/city.rb
class City < ActiveRecord::Base
  has_many :users
end

app/models/disaster.rb
class Disaster < ActiveRecord::Base
  has_many :donations

  scope :ranking_for, ->(id) { joins(:donations).where(original_id: id).group('country').order('sum_amount').sum('amount') }

  def self.find_or_create_from_raw(data)
    find_or_create_by(original_id: data['crisis_eventid']) do |disaster|
      data.delete 'crisis_relatedGDACSResources'
      disaster.raw = data
      logger.info "creating new disater: #{disaster}"
    end
  end
end

app/models/donation.rb
class Donation < ActiveRecord::Base
  belongs_to :user
  belongs_to :disaster

  def self.user_ranking
    group(:user).order('sum_amount desc').limit(20).sum(:amount).map do |user, amount|
      {
        name: user.name,
        image: user.image,
        amount: amount,
        url: user.url
      }
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :city
  has_many :donations
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
 # devise :database_authenticatable, :registerable,
 #        :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, :omniauth_providers => [:facebook]

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def self.from_omniauth(auth)
    token = auth.credentials.token
    city_id = auth.extra.raw_info.location.id rescue nil

    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = "#{auth.uid}@test.com"
      #user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name   # assuming the user model has a name
      user.image = auth.info.image # assuming the user model has an image
      user.city = find_or_create_city_from(city_id, token) if city_id.present?
      user.url = auth.info.urls.Facebook rescue ''
    end
  end

  def self.find_or_create_city_from(city_id, token)
    City.find_or_create_by(original_id: city_id) do |city|
      graph = Koala::Facebook::API.new(token)
      city_object = graph.get_object(city_id, locale: 'en_US')

      city.latitude = city_object['location']['latitude']
      city.longitude = city_object['location']['longitude']
      city.name = city_object['name']
      city.country = city_object['name'].split(',').last.strip()
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def authenticate_user!
    redirect_to sign_in_path unless user_signed_in?
  end

  def new_session_path(scope)
    new_user_session_path
  end

  # Overwriting the sign_out redirect path method
  def after_sign_out_path_for(resource_or_scope)
    sign_in_path
  end
end

app/controllers/disasters_controller.rb
class DisastersController < ApplicationController
def index
    render json: Disaster.page(1).per(50)
  end

  def ranking
    render json: Disaster.ranking_for(params[:id])
  end
end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController
  before_action :set_donation, only: [:show, :edit, :update, :destroy]

  def create
    disaster = Disaster.find_by create_params
    if disaster.present?
      @donation = Donation.new(
        user: current_user,
        disaster: disaster,
        amount: params[:amount],
        country: (current_user.city.country rescue '')
      )
      @donation.save
    end

    redirect_to :root
  end

  def user_ranking
    render json: Donation.user_ranking
  end

  private

  def create_params
    params.require(:disaster).permit(:original_id)
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  before_action :authenticate_user!

  def index
    render layout: false
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_filter :authenticate_user!

  def index
    user_json = current_user.attributes.slice("image", "name")
    user_json['city'] = current_user.city.attributes.slice("original_id", "latitude", "longitude", "name", "country") rescue {}

    render json: user_json
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/disasters/_form.html.slim
= form_for @disaster do |f|
  - if @disaster.errors.any?
    #error_explanation
      h2 = "#{pluralize(@disaster.errors.count, "error")} prohibited this disaster from being saved:"
      ul
        - @disaster.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :desc
    = f.text_field :desc
  .field
    = f.label :original_id
    = f.text_field :original_id
  .actions = f.submit 'Save'

app/views/disasters/edit.html.slim
h1 Editing disaster

== render 'form'

= link_to 'Show', @disaster
'|
= link_to 'Back', disasters_path

app/views/disasters/index.html.slim
h1 Listing disasters

table
  thead
    tr
      th Title
      th Desc
      th Original
      th
      th
      th

  tbody
    - @disasters.each do |disaster|
      tr
        td = disaster.title
        td = disaster.desc
        td = disaster.original_id
        td = link_to 'Show', disaster
        td = link_to 'Edit', edit_disaster_path(disaster)
        td = link_to 'Destroy', disaster, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Disaster', new_disaster_path

app/views/disasters/new.html.slim
h1 New disaster

== render 'form'

= link_to 'Back', disasters_path

app/views/disasters/show.html.slim
p#notice = notice

p
  strong Title:
  = @disaster.title
p
  strong Desc:
  = @disaster.desc
p
  strong Original:
  = @disaster.original_id

= link_to 'Edit', edit_disaster_path(@disaster)
'|
= link_to 'Back', disasters_path

app/views/donations/_form.html.slim
= form_for @donation do |f|
  - if @donation.errors.any?
    #error_explanation
      h2 = "#{pluralize(@donation.errors.count, "error")} prohibited this donation from being saved:"
      ul
        - @donation.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :amount
    = f.number_field :amount
  .field
    = f.label :country
    = f.text_field :country
  .field
    = f.label :user
    = f.text_field :user
  .field
    = f.label :disaster
    = f.text_field :disaster
  .actions = f.submit 'Save'

app/views/donations/edit.html.slim
h1 Editing donation

== render 'form'

= link_to 'Show', @donation
'|
= link_to 'Back', donations_path

app/views/donations/index.html.slim
h1 Listing donations

table
  thead
    tr
      th Amount
      th Country
      th User
      th Disaster
      th
      th
      th

  tbody
    - @donations.each do |donation|
      tr
        td = donation.amount
        td = donation.country
        td = donation.user
        td = donation.disaster
        td = link_to 'Show', donation
        td = link_to 'Edit', edit_donation_path(donation)
        td = link_to 'Destroy', donation, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Donation', new_donation_path

app/views/donations/new.html.slim
h1 New donation

== render 'form'

= link_to 'Back', donations_path

app/views/donations/show.html.slim
p#notice = notice

p
  strong Amount:
  = @donation.amount
p
  strong Country:
  = @donation.country
p
  strong User:
  = @donation.user
p
  strong Disaster:
  = @donation.disaster

= link_to 'Edit', edit_donation_path(@donation)
'|
= link_to 'Back', donations_path

app/views/layouts/application.html.erb
<%= yield %>

app/views/main/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <title>Donathon - Become Charitable with this App.</title>
    <meta name="generator" content="Bootply" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <!--[if lt IE 9]>
      <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <link rel="stylesheet" href="css/stylesheet.css">
    <link rel="stylesheet" href="css/user.css">
    <link rel="stylesheet" href="css/map.css">
    <link rel="stylesheet" href="css/styles.css" >

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= csrf_meta_tags %>
  </head>

  <body id="mainview">
    <div class="wrapper">
      <div class="box">
        <div class="row row-offcanvas row-offcanvas-left">
          <div class="column col-sm-2 col-xs-1 sidebar-offcanvas" id="sidebar" style="position:fixed; right:0">
            <ul class="nav">
              <li>
                <a href="#" data-toggle="offcanvas" class="visible-xs text-center"><i class="glyphicon glyphicon-chevron-right"></i></a>
              </li>
            </ul>
            <div class="user_rank_list">
              <ul id="lg-menu"></ul>
            </div>
            <div class="list-unstyled hidden-xs" id="sidebar-footer">
                <a href="">Made By: Gundam Team</a>
            </div>
            <ul class="nav visible-xs" id="xs-menu">
              <li><a href="#featured" class="text-center"><i class="glyphicon glyphicon-list-alt"></i></a></li>
              <li><a href="#stories" class="text-center"><i class="glyphicon glyphicon-list"></i></a></li>
              <li><a href="#" class="text-center"><i class="glyphicon glyphicon-paperclip"></i></a></li>
              <li><a href="#" class="text-center"><i class="glyphicon glyphicon-refresh"></i></a></li>
            </ul>
          </div>

          <div class="column col-sm-10 col-xs-11">
            <div id="map-title"><h1>The World's Crisis</h1></div>
            <nav id="main-nav" class="navbar navbar-default" role="navigation">
              <div class="container-fluid">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                  </button>
                  <a class="navbar-brand" href="#">
                    <img style="padding-bottom: 8px;" src="images/logo_donation.png" width="140" height="33">
                  </a>
                </div>

                <div class="collapse navbar-collapse">
                  <ul class="nav navbar-nav nav-filter">
                    <li>
                      <a href="#" data-subject='earthquake'><img src="images/icon_earthquake.png" width="20" height="20">Earthquake</a>
                    </li>
                    <li>
                      <a href="#" data-subject='flood'><img src="images/icon_flood.png" width="20" height="20">Flood</a>
                    </li>
                    <li>
                      <a href="#" data-subject='cyclone'><img src="images/icon_typhoon.png" width="20" height="20">Typhoon</a>
                    </li>
                    <li>
                      <a href="#" data-subject='volcanoe'><img src="images/icon_volcano.png" width="20" height="20">Volcano</a>
                    </li>
                  </ul>
                  <ul class="nav navbar-nav navbar-right">
                    <li><a href="/sign_out">Sign Out</a></li>
                    <li><a href="/faq">FAQ</a></li>
                  </ul>
                </div>
              </div>
            </nav>
            <div id="mapdiv">
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="modal fade" id="donateDialog" tabindex="-1" role="dialog" aria-labelledby="Donathon" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
          <h4 class="modal-title" id="donation-modal-label"></h4>
        </div>
        <div class="modal-body">
          <%= form_tag '/donations', id: 'donation-form' do %>
            <div class="form-group">
              <label class="control-label" for="recipient-name">Amount:</label>
              <input class="form-control" name="amount" type="number">
            </div>
            <input id="original_id" type="hidden" name="disaster[original_id]" />
            <button type="submit" class="btn btn-block btn-danger" data-toggle="popover">Donate!</button>
          <% end %>
        </div>
      </div>
    </div>
  </div>

	<!-- script references -->
	<script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>
  <script type="text/javascript" src="http://www.amcharts.com/lib/3/ammap.js"></script>
  <script type="text/javascript" src="http://www.amcharts.com/lib/3/maps/js/continentsLow.js"></script>
  <script type="text/javascript" src="http://www.amcharts.com/lib/3/maps/js/worldLow.js"></script>
  <script type="text/javascript" src="http://www.amcharts.com/lib/3/maps/js/worldHigh.js"></script>
  <script type="text/javascript" src="http://www.amcharts.com/lib/3/themes/none.js"></script>
  <script type="text/javascript" src="js/map.js"></script>
	<script src="js/bootstrap.min.js"></script>
	<script src="js/scripts.js"></script>
  <script src="js/searchButtonOnClick.js"></script>
  <script type="text/javascript">
    $.getJSON('/donations/user_ranking', function(json) {
      $.each(json, function(i, data) {
        fillSideBar(data.amount, data.image, data.name, data.url);
      });
    })

    function fillSideBar(amount, image, name, url){
      $("#lg-menu").append(
        "<li><a href='"+url+"'><img src='"+image+"' />"+name+"<p> has donated "+amount+"USD</p></a></li>"
      )
    }

    function mapResize(){
      $("#mapdiv").css("height",function() {
        return $(window).height() - $("#main-nav").height() - $('#map-title').height();
      })
    }

    mapResize()
    $(window).resize(mapResize);

    $('#donateDialog').on('show.bs.modal', function(e) {
      $that = $(this);
      $that.find('#original_id').val($that.data('data').crisis_eventid);
    });
    $('#donation-form').on('')
  </script>

</body>
</html>